---
- name: Creating Router
  os_router:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      os_user_domain_name: "{{ os_user_domain_name }}"
      os_project_domain_name: "{{ os_project_domain_name }}"
    state: present
    name: "{{ router_name }}"
    network: "{{ router_gateway }}"
    external_fixed_ips:
      - subnet: "{{ router_external_ip_subnet }}"
    interfaces:
      - "{{ router_interfaces }}"