- name: Creating Keypair
  os_keypair:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      os_user_domain_name: "{{ os_user_domain_name }}"
      os_project_domain_name: "{{ os_project_domain_name }}"
    state: present
    name: "{{ keypair_name }}"
    public_key: "{{ public_key }}"